### ISSUE TITLE
Response to question about weather is weird

### ISSUE THREAD

**Issue by s-jse** [stanford-oval/thingpedia-common-devices#175] opened 2020-09-09 22:24 UTC
This is a conversation I had with Almond.

> User: what is the weather like tomorrow?
> Almond: What location do you want sun time info for?

I'm not sure if the agent is misunderstanding the intent, or it is a problem with the response.

**Comment by gcampax** [comment] 2020-09-10 03:14
Dupe of https://github.com/stanford-oval/genie-toolkit/issues/316

**Closed by gcampax** 2020-09-10 03:14 UTC
